if object_id('z.TraceFileAutoGrow') is null
begin
	create table z.TraceFileAutoGrow
	(
		TraceSequence bigint not null constraint DF_z_TraceFileAutoGrow_TraceSequence  default(datediff_big(second,'1900-01-01',getutcdate())*(268435456)|next value for z.SeqGeneralID),
		EventID int not null,
		EventName nvarchar(128) not null,
		TextData nvarchar(max),
		BinaryData varbinary(max),
		DatabaseID int,
		TransactionID bigint,
		LineNumber int,
		NTUserName nvarchar(512),
		NTDomainName nvarchar(512),
		HostName nvarchar(512),
		ClientProcessID int,
		ApplicationName nvarchar(512),
		LoginName nvarchar(512),
		SPID int,
		Duration bigint,
		StartTime datetime,
		EndTime datetime,
		Reads bigint,
		Writes bigint,
		CPU int,
		Permissions bigint,
		Severity int,
		EventSubClass int,
		ObjectID int,
		Success int,
		IndexID int,
		IntegerData int,
		ServerName nvarchar(512),
		EventClass int,
		ObjectType int,
		NestLevel int,
		State int,
		Error int,
		Mode int,
		Handle int,
		ObjectName nvarchar(512),
		DatabaseName nvarchar(512),
		FileName nvarchar(512),
		OwnerName nvarchar(512),
		RoleName nvarchar(512),
		TargetUserName nvarchar(512),
		DBUserName nvarchar(512),
		LoginSid varbinary(max),
		TargetLoginName nvarchar(512),
		TargetLoginSid varbinary(max),
		ColumnPermissions int,
		LinkedServerName nvarchar(512),
		ProviderName nvarchar(512),
		MethodName nvarchar(512),
		RowCounts bigint,
		RequestID int,
		XactSequence bigint,
		EventSequence bigint,
		BigintData1 bigint,
		BigintData2 bigint,
		GUID uniqueidentifier,
		IntegerData2 int,
		ObjectID2 bigint,
		Type int,
		OwnerID int,
		ParentName nvarchar(512),
		IsSystem int,
		Offset int,
		SourceDatabaseID int,
		SqlHandle varbinary(max),
		SessionLoginName nvarchar(512),
		PlanHandle varbinary(max),
		GroupID int,
		constraint PK_z_TraceFileAutoGrow primary key(TraceSequence) with (data_compression = page) on PS_SchemaZPartitionGeneric(TraceSequence)
	) on PS_SchemaZPartitionGeneric(TraceSequence)
end